// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserInfo
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserLoginReq struct {
	Username string `json:"username" comment:"用户名"`
	Password string `json:"password" comment:"密码"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo UserInfo `json:"userInfo"`
}

type UserInfo struct {
	UserBasic
	Username
}

type UserBasic struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Phone    string `json:"phone"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Email    string `json:"email"`
}

type Username struct {
	Username string `json:"username"`
}

type UserUpdateRequest struct {
	UserBasic
}

type UserUpdateResponse struct {
	Flag bool `json:"flag"`
}

type UserDeleteRequest struct {
	UserId int64 `json:"userId"`
}

type UserDeleteResponse struct {
	Flag bool `json:"flag"`
}
