// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/haimait/go-mindoc/app/api/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func SaticRegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	//server.AddRoute(
	//	rest.Route{
	//		Method:  http.MethodGet,
	//		Path:    "/static/:file",
	//		Handler: http.StripPrefix("/static/", http.FileServer(http.Dir("assets"))).ServeHTTP,
	//  },
	//
	////rest.WithPrefix("/api/v1"),
	//)
	//http://127.0.0.1:8081/static/1.png
	server.AddRoute(
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/static/:file",
			Handler: http.StripPrefix("/static/", http.FileServer(http.Dir("assets/static"))).ServeHTTP,
		},
		//rest.WithPrefix("/api/v1"),
	)
}
