// Code generated by goctl. DO NOT EDIT.
package types

type PingReq struct {
}

type PingResp struct {
	Msg string `json:"msg"`
}

type RegisterReq struct {
	UserBasic
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"accessExpire"`
}

type UserLoginReq struct {
	Username string `json:"username" comment:"用户名"`
	Password string `json:"password" comment:"密码"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"accessExpire"`
}

type UserDetailReq struct {
	UserId int64 `json:"userId"`
}

type UserDetailResp struct {
	UserBasic
}

type UserBasic struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	NickName string `json:"nickName"`
	Phone    string `json:"phone"`
	RoleId   int64  `json:"roleId"`
	Avatar   string `json:"avatar"`
	Sex      string `json:"sex"`
	Email    string `json:"email"`
	Remark   string `json:"remark"`
	Status   string `json:"status"`
	AuthKey  string `json:"authKey"`
	AuthType string `json:"authType"`
}

type UserUpdateRequest struct {
	UserBasic
}

type UserUpdateResponse struct {
	Flag bool `json:"flag"`
}

type UserDeleteRequest struct {
	UserId int64 `json:"userId"`
}

type UserDeleteResponse struct {
	Flag bool `json:"flag"`
}
